[package]
name = "video-player"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
gstreamer = "0.24.2"
gstreamer-app = "0.24.2"
gstreamer-video = "0.24.2"
glib = "0.21.3"
slint = "1.13.1"

[build-dependencies]
slint-build = "1.13.1"
